services:
  db:
    image: mysql:8.0
    container_name: oiem_abastible_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3376:3306" # <--- Cambiamos el puerto externo a 3376
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    image: ghcr.io/inntek15dev-lang/abastible-ai-api:latest
    container_name: oiem_abastible_api
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db # Dentro de la red de Docker se siguen viendo por nombre
      - DB_PORT=3306 # Internamente el contenedor MySQL sigue oyendo en 3306
      - DB_USER=root
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
  frontend:
    image: ghcr.io/inntek15dev-lang/abastible-ai-front:latest
    container_name: oiem_abastible_front
    restart: always
    ports:
      - "8087:80" # <--- :D
    environment:
      - VITE_API_URL=https://oiem-abastible-api.inntek.cl/api
    depends_on:
      - api
