FROM node:18-alpine

# Directorio de trabajo
WORKDIR /app

# Instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar el código fuente
COPY . .

# Exponer el puerto
EXPOSE 4000

COPY entrypoint.sh .
RUN tr -d '\r' < entrypoint.sh > entrypoint_temp.sh && \
    mv entrypoint_temp.sh entrypoint.sh && \
    chmod +x entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]